spring.application.name=blog

jwt.secretkey=${JWT_SECRET_KEY:UJz9HKMCAcuJ86UkOzDYFaH9qe5Fs2LamE8PgZ2ubrV}

#Database
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:Aryanksql5!}

#JPA config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
